import type { User, Agency, Switch, MigrationFlow } from './types';

export const users: User[] = [
  {
    id: 'usr_001',
    name: 'Admin',
    email: 'admin@v2mr.com',
    role: 'Admin',
    status: 'Active',
    avatar: '/avatars/01.png',
  },
  {
    id: 'usr_002',
    name: 'Carla Dias',
    email: 'carla.dias@v2mr.com',
    role: 'Coordinator',
    status: 'Active',
    avatar: '/avatars/02.png',
  },
  {
    id: 'usr_003',
    name: 'João Silva',
    email: 'joao.silva@v2mr.com',
    role: 'Analyst',
    status: 'Active',
    avatar: '/avatars/03.png',
  },
  {
    id: 'usr_004',
    name: 'Mariana Costa',
    email: 'mariana.costa@v2mr.com',
    role: 'Analyst',
    status: 'Inactive',
    avatar: '/avatars/04.png',
  },
  {
    id: 'usr_005',
    name: 'Pedro Rocha',
    email: 'pedro.rocha@v2mr.com',
    role: 'Viewer',
    status: 'Active',
    avatar: '/avatars/05.png',
  },
];

export const agencies: Agency[] = [
  {
    code: '1227-0',
    name: 'Ag Centro',
    city: 'São Paulo',
    state: 'SP',
    switchCount: 4,
    migrationDate: '2025-12-01',
    status: 'Awaiting',
  },
  {
    code: '3456-1',
    name: 'Ag Paulista',
    city: 'São Paulo',
    state: 'SP',
    switchCount: 8,
    migrationDate: '2025-11-15',
    status: 'Pending',
  },
  {
    code: '7890-2',
    name: 'Ag Faria Lima',
    city: 'São Paulo',
    state: 'SP',
    switchCount: 6,
    migrationDate: '2025-10-20',
    status: 'In Progress',
  },
  {
    code: '4321-3',
    name: 'Ag Rio Branco',
    city: 'Curitiba',
    state: 'PR',
    switchCount: 5,
    migrationDate: '2024-09-05',
    status: 'Completed',
  },
  {
    code: '8765-4',
    name: 'Ag Batel',
    city: 'Curitiba',
    state: 'PR',
    switchCount: 3,
    migrationDate: '2024-08-22',
    status: 'Completed',
  },
];

export const switches: Switch[] = [
  {
    serialNumber: 'SN123456',
    model: 'S5735-S24T4X',
    hostname: 'SW-AG1227-01',
    agencyCode: '1227-0',
    role: 'Access',
    status: 'In Stock',
  },
  {
    serialNumber: 'SN234567',
    model: 'S5735-S48T4X',
    hostname: 'SW-AG3456-01',
    agencyCode: '3456-1',
    role: 'Access',
    status: 'In Stock',
  },
  {
    serialNumber: 'SN345678',
    model: 'S6730-H24X6C',
    hostname: 'DS-SP-CENTRO-01',
    agencyCode: '1227-0',
    role: 'Distribution',
    status: 'Deployed',
  },
  {
    serialNumber: 'SN456789',
    model: 'S5735-S24T4X',
    hostname: 'SW-AG4321-01',
    agencyCode: '4321-3',
    role: 'Access',
    status: 'Migrated',
  },
  {
    serialNumber: 'SN567890',
    model: 'S5735-S24T4X',
    hostname: 'SW-AG8765-01',
    agencyCode: '8765-4',
    role: 'Access',
    status: 'Faulty',
  },
];

export const migrationFlows: MigrationFlow[] = [
  {
    id: 'flow_001',
    agencyCode: '1227-0',
    agencyName: 'Ag Centro',
    status: 'Planning',
    assignedAnalyst: 'João Silva',
    lastUpdate: '2024-06-18',
  },
  {
    id: 'flow_002',
    agencyCode: '3456-1',
    agencyName: 'Ag Paulista',
    status: 'Site Survey',
    assignedAnalyst: 'Mariana Costa',
    lastUpdate: '2024-06-17',
  },
  {
    id: 'flow_003',
    agencyCode: '7890-2',
    agencyName: 'Ag Faria Lima',
    status: 'Configuration',
    assignedAnalyst: 'João Silva',
    lastUpdate: '2024-06-19',
  },
  {
    id: 'flow_004',
    agencyCode: '4321-3',
    agencyName: 'Ag Rio Branco',
    status: 'Completed',
    assignedAnalyst: 'Carla Dias',
    lastUpdate: '2024-05-30',
  },
];
